name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Download dependencies
      run: go mod download

    - name: Build binaries
      run: |
        mkdir -p release
        GOOS=linux GOARCH=amd64 go build -o release/hs.linux
        GOOS=darwin GOARCH=amd64 go build -o release/hs.mac  
        GOOS=darwin GOARCH=arm64 go build -o release/hs.m1mac

    - name: Create Release
      run: |
        # Check for prerelease
        PRERELEASE_FLAG=""
        if [[ "${{ github.ref_name }}" == v0* ]]; then
          PRERELEASE_FLAG="--prerelease"
        fi

        # Create release with tag annotation notes (will fail if tag is not annotated)
        if ! gh release create ${{ github.ref_name }} \
             release/hs.linux \
             release/hs.mac \
             release/hs.m1mac \
             --title "${{ github.ref_name }}" \
             --notes-from-tag \
             $PRERELEASE_FLAG; then
          echo "❌ Release failed"
          exit 1
        fi

        echo "✅ Release created successfully!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
